"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = "log"
conflict-marker-style = "git"
editor = "code.cmd --wait --new-window" # VS Code
diff-instructions = false
diff-editor = "vscode"
merge-editor = "vscode"

[user]
name = "danybeam"
email = "danybeam@gmail.com"

[aliases]
# `jj l` shows commits on the working-copy commit's (anonymous) bookmark
# compared to the `main` bookmark
l = ["log", "-r", "(main..@):: | (main..@)-"]
fwd = ["bookmark", "move", "--from", "main", "--to", "here"]

[revset-aliases]
HEAD = "@"
here = "@"

[merge-tools.vscode]
diff-invocation-mode = "file-by-file"
edit-args = ["--wait", "--new-window", "--diff", "$left", "$right"]
diff-args = ["--wait", "--new-window", "--diff", "$left", "$right"]
